export const t = {
  connect: {
    title: (account: string) => `Conectar em ${account}`,
    detail:
      "O ProofHub não tem OAuth, então a chave é copiada uma vez. O navegador abre na página de acesso à API: copie a chave por lá e volte. O VS Code observa a área de transferência e conecta sozinho, sem você colar nada aqui.",
    openBrowser: "Abrir o ProofHub e esperar a chave",
    pasteMyself: "Prefiro colar a chave",
    changeAccount: "Trocar de conta",
    waiting: "Esperando a chave do ProofHub",
    waitingHint: "Copie a chave no navegador",
    notFound: "Nenhuma chave válida apareceu na área de transferência.",
    tryPaste: "Colar na mão",
    accountTitle: "Conta do ProofHub",
    accountPrompt: "O endereço da sua conta do ProofHub",
    accountInvalid: "Informe um endereço como acme.proofhub.com",
    keyPrompt: "Cole a chave da API mostrada na tela de acesso à API",
    keyEmpty: "A chave não pode ficar vazia",
    checking: (account: string) => `Conferindo a chave de ${account}`,
    retry: "Tentar de novo",
    connectedAs: (name: string) => `ProofHub conectado como ${name}.`,
    connected: "ProofHub conectado.",
    removed: "Chave do ProofHub removida desta máquina.",
    rejected: "O ProofHub recusou a chave. Rode ProofHub: Conectar para informar outra.",
    failure: (status: number, message: string) => `Erro ${status} do ProofHub: ${message}`,
  },
  me: {
    whoAreYou: "Qual desses é você",
    whoAreYouHint: "A conta não expõe quem é o dono da chave, então escolha uma vez só",
  },
  common: {
    connectFirst: "Conecte no ProofHub primeiro.",
    loading: "Carregando…",
    tryAgain: "Tentar de novo",
    nobody: "Ninguém",
    sectionFailed: (motivo: string) => `Não deu para carregar esta parte: ${motivo}`,
  },
  tree: {
    subtasks: (count: number) => (count === 1 ? "1 subtarefa" : `${count} subtarefas`),
  },
  task: {
    newTitle: (list: string) => `Nova tarefa em ${list}`,
    titlePrompt: "Título da tarefa",
    titleEmpty: "O título não pode ficar vazio",
    assignTo: "Responsável",
    duePrompt: "AAAA-MM-DD, ou deixe em branco",
    dueTitle: "Prazo",
    dueInvalid: "Use o formato AAAA-MM-DD",
    pickList: "Selecione uma lista para criar a tarefa.",
    created: (list: string) => `Tarefa criada em ${list}.`,
    completed: (title: string) => `${title} concluída.`,
    commentTitle: (title: string) => `Comentar em ${title}`,
    commentPrompt: "Seu comentário",
    commentEmpty: "O comentário não pode ficar vazio",
    commentPosted: "Comentário publicado.",
  },
  time: {
    logTitle: (title: string) => `Lançar horas em ${title}`,
    hoursPrompt: "Horas no formato H:MM",
    hoursInvalid: "Use o formato H:MM",
    noTimesheet: "Este projeto não tem planilha de horas para receber o lançamento.",
    timesheet: "Planilha de horas",
    whatPrompt: "No que você trabalhou",
    logged: (hours: string, title: string) => `${hours} lançadas em ${title}.`,
    alreadyRunning: (title: string) => `Já existe um cronômetro rodando em ${title}.`,
    notRunning: "Nenhum cronômetro está rodando.",
    stopHint: "Clique para parar e lançar as horas no ProofHub",
  },
  mine: {
    collecting: "Reunindo suas tarefas abertas",
    progress: (project: string, done: number, total: number) => `${project} (${done}/${total})`,
    none: "Você não tem tarefas abertas.",
    title: (count: number) => `Suas tarefas abertas (${count})`,
  },
  link: {
    title: "Abrir um link do ProofHub",
    prompt: "Cole um link do ProofHub para revelar o item na árvore",
    invalid: "Isso não é um link do ProofHub",
    looking: "Procurando o link",
    unknownProject: "Esse projeto não aparece com a sua chave.",
    otherAccount: (link: string, current: string) =>
      `Esse link é da conta ${link}, mas você está conectado em ${current}.`,
  },
  layout: {
    cannotMove: "Esta versão do VS Code não move painéis por comando. Arraste o ícone do ProofHub para a barra da direita uma vez.",
  },
  flow: {
    loadingProjects: "Carregando projetos",
    loadingLists: "Carregando listas",
    pickProject: "Em qual projeto",
    pickList: (project: string) => `Em qual lista de ${project}`,
    noLists: (project: string) => `O projeto ${project} não tem nenhuma lista para receber a tarefa.`,
    assignTo: "Responsáveis",
    assignHint: "Selecione quantas pessoas quiser, ou nenhuma",
    estimateTitle: "Tempo estimado",
    estimatePrompt: "Estimativa no formato H:MM, ou deixe em branco",
  },
  filter: {
    title: "Filtrar tarefas",
    search: "Buscar tarefas",
    searchPrompt: "Busca por título e descrição, com várias palavras",
    mine: "Somente as minhas",
    mineDetail: "Tarefas atribuídas a você",
    hideCompleted: "Esconder concluídas",
    hideCompletedDetail: "Mostrar apenas o que continua em aberto",
    overdue: "Somente atrasadas",
    overdueDetail: "Prazo já vencido e ainda em aberto",
    clear: "Limpar filtros",
    sortTitle: "Ordenar tarefas",
    sort: {
      list: "Ordem da lista",
      listDetail: "Como o ProofHub devolve",
      due: "Prazo",
      dueDetail: "As mais próximas primeiro, sem prazo por último",
      title: "Título",
      titleDetail: "Em ordem alfabética",
      assigned: "Sem responsável primeiro",
      assignedDetail: "Ajuda a achar o que ficou sem dono",
    },
    active: (parts: string) => `filtrando: ${parts}`,
  },
  report: {
    title: "Horas no ProofHub",
    loading: "Somando suas horas",
    today: "Hoje",
    week: "Nesta semana",
    month: "Neste mês",
    total: "No período",
    estimated: "Estimado em aberto",
    days: "Últimos dias",
    weeks: "Últimas semanas",
    months: "Meses",
    projects: "Por projeto",
    entries: "Lançamentos",
    noEntries: "Nenhuma hora lançada no período.",
    week_of: (day: string) => `semana de ${day}`,
    onlyMine: "Somente minhas horas",
    everyone: "Horas de toda a equipe",
  },
  detail: {
    status: { open: "em aberto", done: "concluída" },
    due: (date: string) => `prazo ${date}`,
    estimate: (hours: string) => `estimativa ${hours}`,
    complete: "Concluir",
    reopen: "Reabrir",
    startTimer: "Iniciar cronômetro",
    stopTimer: "Parar cronômetro",
    openBrowser: "Abrir no ProofHub",
    refresh: "Atualizar",
    description: "Descrição",
    noDescription: "Sem descrição.",
    subtasks: "Subtarefas",
    noSubtasks: "Nenhuma subtarefa.",
    newSubtask: "Nova subtarefa",
    add: "Adicionar",
    time: "Horas",
    noTime: "Nenhuma hora lançada nesta tarefa.",
    logHours: "Lançar",
    whatPlaceholder: "No que você trabalhou",
    comments: "Comentários",
    noComments: "Nenhum comentário ainda.",
    writeComment: "Escreva um comentário",
    comment: "Comentar",
    sendHint: "Cmd+Enter envia",
  },
};
